name: My First Playbook

on : [push]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome msg
              run: echo "My first Githuv Actions Job"
            
            - name: List files
              run: ls

            - name: Read file
              run: cat README.md